# -*- coding: utf-8 -*-
"""统一配置层 · registry **批量条目（生成件）**。

由 `scripts/gen_config_registry.py` 生成；来源 = `.tmp/param_inventory.json`
（可调参数全量盘点）+ 源码 AST 逐位复核。

**本文件是生成件，不要手改。** 生成块一经产出即成为 registry 真源的一部分
（冻结快照）：改默认值请改**源码**，守卫 `md_cg/config_registry_guard.py`
会转红；补齐登记请重跑生成器或手工改登记（两条路都会过守卫）。

字段（元组序，与 `cp.entry_from_row` 对齐）：
    name, face, layer, kind, tunable, value_repr, value_type, domain,
    env_name, semantic, anchor_how, anchor_file, anchor_symbol,
    status, evidence, since, notes

"""
from __future__ import annotations

ROW_FIELDS = (
    "name", "face", "layer", "kind", "tunable", "value_repr",
    "value_type", "domain", "env_name", "semantic", "anchor_how",
    "anchor_file", "anchor_symbol", "status", "evidence", "since",
    "notes",
)

# fmt: off
CONST_ROWS = [
    ('R1_MAX_SHARE', 'CALIB', 'calib', 'const', True, '0.9', 'float', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/admission.py', 'R1_MAX_SHARE', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('R1_MIN_ONE', 'CALIB', 'calib', 'const', True, '1', 'int', '见 default（阈值/权重）', '', '', 'const_assign', 'md_cg/admission.py', 'R1_MIN_ONE', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('R2_MIN_RECENT', 'CALIB', 'calib', 'const', True, '1', 'int', '见 default（阈值/权重）', '', '', 'const_assign', 'md_cg/admission.py', 'R2_MIN_RECENT', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('R2_MIN_TOTAL', 'CALIB', 'calib', 'const', True, '1', 'int', '见 default（阈值/权重）', '', '', 'const_assign', 'md_cg/admission.py', 'R2_MIN_TOTAL', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('R3_MIN_ROLLBACKS', 'CALIB', 'calib', 'const', True, '1', 'int', '见 default（阈值/权重）', '', '', 'const_assign', 'md_cg/admission.py', 'R3_MIN_ROLLBACKS', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('R4_MAX_RATE', 'CALIB', 'calib', 'const', True, '0.2', 'float', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/admission.py', 'R4_MAX_RATE', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('R4_SUBWINDOWS', 'TUNE', 'tune', 'const', True, '3', 'int', '见 default（超时/时间窗）', '', '', 'const_assign', 'md_cg/admission.py', 'R4_SUBWINDOWS', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('R4_SUBWINDOW_D', 'TUNE', 'tune', 'const', True, '10.0', 'float', '见 default（超时/时间窗）', '', '', 'const_assign', 'md_cg/admission.py', 'R4_SUBWINDOW_D', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('TTL_DEFAULT', 'TUNE', 'tune', 'const', True, '60.0', 'float', '见 default（超时/时间窗）', '', '', 'const_assign', 'md_cg/admission.py', 'TTL_DEFAULT', 'calibrating', '读数缓存 TTL（秒）——探针定：在役库一次完整扫描 ≈ 0.3s（主成本 =', 'unknown', ''),
    ('WINDOW_LONG_D', 'TUNE', 'tune', 'const', True, '30', 'int', '见 default（超时/时间窗）', '', '', 'const_assign', 'md_cg/admission.py', 'WINDOW_LONG_D', 'calibrating', '裁定③：短期 = 3 天（R2 活性读数）；长期 = 30 天（R1/R3/R4 能力读数）。', 'unknown', ''),
    ('WINDOW_SHORT_D', 'TUNE', 'tune', 'const', True, '3', 'int', '见 default（超时/时间窗）', '', '', 'const_assign', 'md_cg/admission.py', 'WINDOW_SHORT_D', 'calibrating', '裁定③：短期 = 3 天（R2 活性读数）；长期 = 30 天（R1/R3/R4 能力读数）。', 'unknown', ''),
    ('DEFAULT_CAP', 'TUNE', 'tune', 'const', True, '8', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/auditview.py', 'DEFAULT_CAP', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('BUDGET_MAX_ENV', 'CALIB', 'calib', 'const', False, "'MDCG_EXPLORE_BUDGET_MAX'", 'str', '见 default（env名常量）', '', '', 'const_assign', 'md_cg/autonomy.py', 'BUDGET_MAX_ENV', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('BUDGET_WINDOW_DEFAULT', 'TUNE', 'tune', 'const', True, '86400.0', 'float', '见 default（超时/时间窗）', '', '', 'const_assign', 'md_cg/autonomy.py', 'BUDGET_WINDOW_DEFAULT', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('BUDGET_WINDOW_ENV', 'TUNE', 'tune', 'const', False, "'MDCG_EXPLORE_BUDGET_WINDOW'", 'str', '见 default（env名常量）', '', '', 'const_assign', 'md_cg/autonomy.py', 'BUDGET_WINDOW_ENV', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('GAIN_COOLDOWN', 'CALIB', 'calib', 'const', True, '3600.0', 'float', '见 default（阈值/权重）', '', '', 'const_assign', 'md_cg/autonomy.py', 'GAIN_COOLDOWN', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：冷却秒数：过期后 σ 回 1.0（给探索机会，不永久冻结）'),
    ('GAIN_WINDOW', 'TUNE', 'tune', 'const', True, '2', 'int', '见 default（超时/时间窗）', '', '', 'const_assign', 'md_cg/autonomy.py', 'GAIN_WINDOW', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：连续 GAIN_WINDOW 次终态无变化 → 视为无增益'),
    ('_GAIN_STUCK', 'TUNE', 'tune', 'const', False, "('carried', 'unresolved', 'unknowable', 'no_anchor')", 'tuple', '见 default（枚举/表）', '', '', 'const_assign', 'md_cg/autonomy.py', '_GAIN_STUCK', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('E_WEIGHT', 'CALIB', 'calib', 'const', False, "'E'", 'str', '见 default（枚举/名称）', '', '', 'const_assign', 'md_cg/autonomy_modes.py', 'E_WEIGHT', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：权重与生命周期'),
    ('_SETTLEMENT', 'TUNE', 'tune', 'const', False, "{'configured': None, 'effective': None, 'settled': False, 'admission': None, 'alerts': [], 'root': None, 't': 0.0, 'error': None}", 'dict', '见 default（枚举/表）', '', '', 'const_assign', 'md_cg/autonomy_modes.py', '_SETTLEMENT', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('BATCH_DEFAULT', 'TUNE', 'tune', 'const', False, "'backfill'", 'str', '见 default（枚举/名称）', '', '', 'const_assign', 'md_cg/backfill.py', 'BATCH_DEFAULT', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('FIX_BATCH_DEFAULT', 'TUNE', 'tune', 'const', False, "'cond_fix'", 'str', '见 default（枚举/名称）', '', '', 'const_assign', 'md_cg/backfill.py', 'FIX_BATCH_DEFAULT', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('_CAP_TEMPLATE_LINES', 'TUNE', 'tune', 'const', False, "('验证方式',)", 'tuple', '见 default（枚举/表）', '', '', 'const_assign', 'md_cg/backfill.py', '_CAP_TEMPLATE_LINES', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('DEFAULT_EDGE_WEIGHT', 'CALIB', 'calib', 'const', True, '0.5', 'float', '见 default（阈值/权重）', '', '', 'const_assign', 'md_cg/chain.py', 'DEFAULT_EDGE_WEIGHT', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('EDGE_WEIGHTS', 'CALIB', 'calib', 'const', False, "{'causal': 0.85, 'similar': 0.75, 'hierarchical': 0.7, 'part_of': 0.7, 'parent_of': 0.7, 'applies_to': 0.7, 'sequential': 0.6, 'spatial_contains': 0.55, 'spatial_adjacent': 0.5, 'spatial_connected': 0.5, 'correlational': 0.45, 'cyclic': 0.35, 'opposite': 0.3, 'reference': 0.5}", 'dict', '见 default（枚举/表）', '', '', 'const_assign', 'md_cg/chain.py', 'EDGE_WEIGHTS', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('MAX_DEPTH_DEFAULT', 'TUNE', 'tune', 'const', True, '5', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/chain.py', 'MAX_DEPTH_DEFAULT', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('MAX_DEPTH_HARD', 'TUNE', 'tune', 'const', True, '64', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/chain.py', 'MAX_DEPTH_HARD', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('MAX_NODES_DEFAULT', 'CALIB', 'calib', 'const', True, '500', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/chain.py', 'MAX_NODES_DEFAULT', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('MAX_DOC', 'CALIB', 'calib', 'const', True, '400', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/codeindex.py', 'MAX_DOC', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('BATCH_LIMIT', 'TUNE', 'tune', 'const', True, '10', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/coldverify.py', 'BATCH_LIMIT', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('POLL_INTERVAL', 'TUNE', 'tune', 'const', True, '2.0', 'float', '见 default（超时/时间窗）', '', '', 'const_assign', 'md_cg/coldverify.py', 'POLL_INTERVAL', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('DUP_GROUP_MAX', 'CALIB', 'calib', 'const', True, '200', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/conformance.py', 'DUP_GROUP_MAX', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('THRESHOLDS', 'CALIB', 'calib', 'const', False, "{'stratum_ratio_max': 0.6, 'stratum_target': 0.3, 'role_coverage_min': 0.9, 'evidence_coverage_min': 0.5, 'analysis_coverage_min': 0.9, 'reach_ratio_min': 0.3, 'gate_sample_min': 20, 'min_nodes': 200}", 'dict', '见 default（枚举/表）', '', '', 'const_assign', 'md_cg/conformance.py', 'THRESHOLDS', 'calibrating', '注：触达率随 _access.log 滚动追加而单调增长，9-15 快照 7.0% → 09-16 实测 8.7%，', 'unknown', ''),
    ('MAX_DEPTH', 'TUNE', 'tune', 'const', True, '3', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/consistency.py', 'MAX_DEPTH', 'uncalibrated', 'MAX_DEPTH = 3        # L2 递归深度上限（对齐 :273）', 'unknown', '源码注释：L2 递归深度上限（对齐 :273）'),
    ('MAX_NODES', 'CALIB', 'calib', 'const', True, '60', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/consistency.py', 'MAX_NODES', 'uncalibrated', 'MAX_DEPTH = 3        # L2 递归深度上限（对齐 :273）；MAX_NODES = 60       # L2 递归展开节点上限（对齐 :273）', 'unknown', '源码注释：L2 递归展开节点上限（对齐 :273）'),
    ('MAX_SCAN', 'CALIB', 'calib', 'const', True, '200', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/consistency.py', 'MAX_SCAN', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：单次检测最多比对的既有节点数（防 O(N) 爆炸）'),
    ('MIN_GAIN', 'CALIB', 'calib', 'const', True, '0.15', 'float', '见 default（阈值/权重）', '', '', 'const_assign', 'md_cg/consistency.py', 'MIN_GAIN', 'uncalibrated', 'MAX_DEPTH = 3        # L2 递归深度上限（对齐 :273）；MAX_NODES = 60       # L2 递归展开节点上限（对齐 :273）', 'unknown', '源码注释：信息增益门槛：候选空间减少比例低于此值即停（对齐 :273）'),
    ('SEPARATION_REL', 'CALIB', 'calib', 'const', False, "'distinct_from'", 'str', '见 default（枚举/名称）', '', '', 'const_assign', 'md_cg/consistency.py', 'SEPARATION_REL', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('DEFAULT_MAX_TOKENS', 'CALIB', 'calib', 'const', True, '200000', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/consolidate.py', 'DEFAULT_MAX_TOKENS', 'calibrating', 'reasoning_tokens 计入 max_tokens，预算过小 = content 被思考吃光 = issue #24 根因）。', 'unknown', ''),
    ('INDUCE_MAX_NODES', 'CALIB', 'calib', 'const', True, '400', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/consolidate.py', 'INDUCE_MAX_NODES', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('INDUCE_MAX_TERMS', 'CALIB', 'calib', 'const', True, '6', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/consolidate.py', 'INDUCE_MAX_TERMS', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('INDUCE_MIN_CLUSTER', 'CALIB', 'calib', 'const', True, '3', 'int', '见 default（阈值/权重）', '', '', 'const_assign', 'md_cg/consolidate.py', 'INDUCE_MIN_CLUSTER', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('INDUCE_MIN_JACCARD', 'CALIB', 'calib', 'const', True, '0.3', 'float', '见 default（阈值/权重）', '', '', 'const_assign', 'md_cg/consolidate.py', 'INDUCE_MIN_JACCARD', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('MAX_BODY_CHARS', 'CALIB', 'calib', 'const', True, '3000', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/consolidate.py', 'MAX_BODY_CHARS', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：正文截断（控制 token，且条件主要来自开头）'),
    ('MAX_TERMS', 'CALIB', 'calib', 'const', True, '8', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/consolidate.py', 'MAX_TERMS', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：单字段候选条数上限'),
    ('MAX_TERM_LEN', 'CALIB', 'calib', 'const', True, '40', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/consolidate.py', 'MAX_TERM_LEN', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：单条候选长度上限'),
    ('MAX_TOKENS_ENV', 'CALIB', 'calib', 'const', False, "'MDCG_LLM_MAX_TOKENS'", 'str', '见 default（env名常量）', '', '', 'const_assign', 'md_cg/consolidate.py', 'MAX_TOKENS_ENV', 'calibrating', 'reasoning_tokens 计入 max_tokens，预算过小 = content 被思考吃光 = issue #24 根因）。', 'unknown', ''),
    ('CROSSCHECK_BATCH', 'TUNE', 'tune', 'const', False, "'crosscheck'", 'str', '见 default（枚举/名称）', '', '', 'const_assign', 'md_cg/crosscheck.py', 'CROSSCHECK_BATCH', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('DEFAULT_WINDOW', 'TUNE', 'tune', 'const', True, '200', 'int', '见 default（超时/时间窗）', '', '', 'const_assign', 'md_cg/d_meta.py', 'DEFAULT_WINDOW', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('_CACHE_MAX', 'TUNE', 'tune', 'const', True, '64', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/d_meta.py', '_CACHE_MAX', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：进程内缓存条目上限（超出即清空，无后台线程）'),
    ('DEFAULT_SENSITIVITY', 'CALIB', 'calib', 'const', False, "'internal'", 'str', '见 default（枚举/名称）', '', '', 'const_assign', 'md_cg/docindex.py', 'DEFAULT_SENSITIVITY', 'uncalibrated', '审计时看不出意图）。且路径段命中私有提示时**再保守一档降为 private**：', 'unknown', ''),
    ('MAX_DOC', 'CALIB', 'calib', 'const', True, '400', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/docindex.py', 'MAX_DOC', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('MAX_LEVEL', 'CALIB', 'calib', 'const', True, '3', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/docindex.py', 'MAX_LEVEL', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：只切 level<=3'),
    ('MAX_SUMMARY', 'CALIB', 'calib', 'const', True, '200', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/docindex.py', 'MAX_SUMMARY', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：「执行」栏摘要上限'),
    ('MIN_BODY', 'CALIB', 'calib', 'const', True, '200', 'int', '见 default（阈值/权重）', '', '', 'const_assign', 'md_cg/docindex.py', 'MIN_BODY', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：直接正文 < 200 字且无子节 → 合并进父节'),
    ('MAX_ITEMS', 'CALIB', 'calib', 'const', True, '500', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/evidence.py', 'MAX_ITEMS', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：单包条目上限（防灌包）'),
    ('MAX_TEXT', 'CALIB', 'calib', 'const', True, '4000', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/evidence.py', 'MAX_TEXT', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：单条正文上限'),
    ('DETERMINISTIC_BASIS', 'CALIB', 'calib', 'const', False, "('data', 'measurement', 'compiler', 'test', 'formal_proof')", 'tuple', '见 default（枚举/表）', '', '', 'const_assign', 'md_cg/forgetting.py', 'DETERMINISTIC_BASIS', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('IMPORTANCE_MIN', 'CALIB', 'calib', 'const', True, '0.3', 'float', '见 default（阈值/权重）', '', '', 'const_assign', 'md_cg/forgetting.py', 'IMPORTANCE_MIN', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：重要度 < 此值 → 不予写入'),
    ('LONGTERM_KEEP', 'TUNE', 'tune', 'const', True, '10', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/forgetting.py', 'LONGTERM_KEEP', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：保留最近 N 个断面（多了自动清理）'),
    ('MAX_BITS', 'CALIB', 'calib', 'const', True, '4.0', 'float', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/forgetting.py', 'MAX_BITS', 'uncalibrated', 'PROTECT_IMPORTANCE = 0.70   # 对齐 tool_table：≥0.7 触发不可遗忘保护', 'unknown', '源码注释：自信息归一化上限（dup=0 时 4.0 bit）'),
    ('MAX_COMPARE', 'CALIB', 'calib', 'const', True, '240', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/forgetting.py', 'MAX_COMPARE', 'uncalibrated', 'PROTECT_IMPORTANCE = 0.70   # 对齐 tool_table：≥0.7 触发不可遗忘保护', 'unknown', '源码注释：单次重复检测最多比对的同层节点数（写入非热路径）'),
    ('MERGE_SOURCES_KEEP', 'TUNE', 'tune', 'const', True, '20', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/forgetting.py', 'MERGE_SOURCES_KEEP', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：fm.merge_sources 只保留最近 N 条「新写入方归属」'),
    ('NOVELTY_MIN', 'CALIB', 'calib', 'const', True, '0.15', 'float', '见 default（阈值/权重）', '', '', 'const_assign', 'md_cg/forgetting.py', 'NOVELTY_MIN', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：新信息 < 此值 → 视为无新信息'),
    ('SOURCE_WEIGHT', 'CALIB', 'calib', 'const', False, "{'external_surprising': 1.0, 'unknown': 0.6, 'self_generated': 0.5, 'internal_deterministic': 0.25}", 'dict', '见 default（枚举/表）', '', '', 'const_assign', 'md_cg/forgetting.py', 'SOURCE_WEIGHT', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('FRESHNESS_ENV', 'CALIB', 'calib', 'const', False, "'MDCG_FRESHNESS'", 'str', '见 default（env名常量）', '', '', 'const_assign', 'md_cg/freshness.py', 'FRESHNESS_ENV', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('REFRESH_PARAMS', 'CALIB', 'calib', 'const', False, "{'rehearsal_threshold': 0.7, 'degrade_threshold': 0.2, 'gain': 0.01, 'cycle': 10, 'degrade_max_access': 2, 'source': 'md_cg/whitebox_kb/aeis_core/core.py:4801-4831 consolidate_cycle(rehearsal_threshold=0.7, degrade_threshold=0.2, gain=0.01)'}", 'dict', '见 default（枚举/表）', '', '', 'const_assign', 'md_cg/freshness.py', 'REFRESH_PARAMS', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('_NONOBJECT_SAMPLE_CAP', 'TUNE', 'tune', 'const', True, '32', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/fsutil.py', '_NONOBJECT_SAMPLE_CAP', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：样本上限：记账要有界，不随坏行线性涨'),
    ('_SHARD_DIR_SAMPLE_CAP', 'TUNE', 'tune', 'const', True, '8', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/fsutil.py', '_SHARD_DIR_SAMPLE_CAP', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：样本上限：记账有界，不随事件线性涨'),
    ('_TRANSIENT_READ_SAMPLE_CAP', 'TUNE', 'tune', 'const', True, '32', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/fsutil.py', '_TRANSIENT_READ_SAMPLE_CAP', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：样本上限：记账要有界，不随失败次数线性涨'),
    ('_TRANSIENT_READ_WARN_CAP', 'TUNE', 'tune', 'const', True, '32', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/fsutil.py', '_TRANSIENT_READ_WARN_CAP', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('DEFAULT_LIMIT', 'TUNE', 'tune', 'const', True, '10', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/goal_gen.py', 'DEFAULT_LIMIT', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('S2_PENDING_MIN', 'CALIB', 'calib', 'const', True, '3', 'int', '见 default（阈值/权重）', '', '', 'const_assign', 'md_cg/goal_gen.py', 'S2_PENDING_MIN', 'calibrating', '---- 六源阈值（**首版保守缺省、观察期标定**，裁定第 10 条） -------------------', 'unknown', '源码注释：沿用 insight.outlook 既有建议阈值（:423 pending>=3）'),
    ('S3_CCG_MIN', 'CALIB', 'calib', 'const', True, '5', 'int', '见 default（阈值/权重）', '', '', 'const_assign', 'md_cg/goal_gen.py', 'S3_CCG_MIN', 'calibrating', '---- 六源阈值（**首版保守缺省、观察期标定**，裁定第 10 条） -------------------；S3_CCG_MIN = 5              # 单层无验证基底节点数阈值（保守）', 'unknown', '源码注释：单层无验证基底节点数阈值（保守）'),
    ('S4_BLINDSPOT_MIN', 'CALIB', 'calib', 'const', True, '3', 'int', '见 default（阈值/权重）', '', '', 'const_assign', 'md_cg/goal_gen.py', 'S4_BLINDSPOT_MIN', 'uncalibrated', 'S3_CCG_MIN = 5              # 单层无验证基底节点数阈值（保守）', 'unknown', '源码注释：与 blindspot_tickets._JUDGE research 判据同源（:30）'),
    ('S6_MISSING_MIN', 'CALIB', 'calib', 'const', True, '3', 'int', '见 default（阈值/权重）', '', '', 'const_assign', 'md_cg/goal_gen.py', 'S6_MISSING_MIN', 'uncalibrated', 'S3_CCG_MIN = 5              # 单层无验证基底节点数阈值（保守）；S6_MISSING_MIN = 3          # 单一缺失维度计分阈值（保守）', 'unknown', '源码注释：单一缺失维度计分阈值（保守）'),
    ('MAX_NODES', 'CALIB', 'calib', 'const', True, '256', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/hotcache.py', 'MAX_NODES', 'calibrating', '为 567 节点，缺省 256 会持续 LRU 淘汰，issue #28：容量应可配或自适应）', 'unknown', ''),
    ('MAX_QUERIES', 'CALIB', 'calib', 'const', True, '64', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/hotcache.py', 'MAX_QUERIES', 'calibrating', '为 567 节点，缺省 256 会持续 LRU 淘汰，issue #28：容量应可配或自适应）', 'unknown', ''),
    ('QUERY_TTL', 'TUNE', 'tune', 'const', True, '300.0', 'float', '见 default（超时/时间窗）', '', '', 'const_assign', 'md_cg/hotcache.py', 'QUERY_TTL', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('_ALPHA_FMT', 'TUNE', 'tune', 'const', False, "('png', 'tif', 'tiff')", 'tuple', '见 default（枚举/表）', '', '', 'const_assign', 'md_cg/imgskill.py', '_ALPHA_FMT', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('_GAMMA_RANGE', 'TUNE', 'tune', 'const', False, '(0.0, 10.0)', 'tuple', '见 default（枚举/表）', '', '', 'const_assign', 'md_cg/imgskill.py', '_GAMMA_RANGE', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：gamma 开区间下界 / 闭区间上界'),
    ('_MAGICK_TIMEOUT', 'TUNE', 'tune', 'const', True, '120.0', 'float', '见 default（超时/时间窗）', '', '', 'const_assign', 'md_cg/imgskill.py', '_MAGICK_TIMEOUT', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('_SIGMA_MAX', 'TUNE', 'tune', 'const', True, '100.0', 'float', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/imgskill.py', '_SIGMA_MAX', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：blur/sharpen 的 sigma 上限'),
    ('C1_WINDOW_MIN', 'TUNE', 'tune', 'const', True, '0.6', 'float', '见 default（超时/时间窗）', '', '', 'const_assign', 'md_cg/insight.py', 'C1_WINDOW_MIN', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：C1 可检索度开窗门槛'),
    ('CER_MIN_SAMPLES', 'CALIB', 'calib', 'const', True, '20', 'int', '见 default（阈值/权重）', '', '', 'const_assign', 'md_cg/insight.py', 'CER_MIN_SAMPLES', 'uncalibrated', 'IMPORTANCE_FLOOR = 0.9             # verified 后的重要度保底（对齐工具表）', 'unknown', '源码注释：样本 < 20 不判定层状态'),
    ('V1_MIN_EVIDENCE', 'CALIB', 'calib', 'const', True, '3', 'int', '见 default（阈值/权重）', '', '', 'const_assign', 'md_cg/insight.py', 'V1_MIN_EVIDENCE', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：V1（可检索/被引用）需 ≥3 条才成立'),
    ('_GIT_TIMEOUT_S', 'TUNE', 'tune', 'const', True, '120', 'int', '见 default（超时/时间窗）', '', '', 'const_assign', 'md_cg/interop.py', '_GIT_TIMEOUT_S', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('HISTORY_KEEP', 'TUNE', 'tune', 'const', True, '20', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/lifecycle.py', 'HISTORY_KEEP', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('CAP_ALIGNED', 'TUNE', 'tune', 'const', True, '0.8', 'float', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/links.py', 'CAP_ALIGNED', 'calibrating', '---- 信任数值（未标定占位；方向性约束由宪章第七条确定：降快于升）----------', 'unknown', ''),
    ('CAP_INCOMPLETE', 'TUNE', 'tune', 'const', True, '0.6', 'float', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/links.py', 'CAP_INCOMPLETE', 'calibrating', '---- 信任数值（未标定占位；方向性约束由宪章第七条确定：降快于升）----------', 'unknown', '源码注释：未声明单元映射（子智能体级）'),
    ('CAP_ISOLATED', 'TUNE', 'tune', 'const', True, '0.0', 'float', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/links.py', 'CAP_ISOLATED', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('CAP_MISALIGNED', 'TUNE', 'tune', 'const', True, '0.3', 'float', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/links.py', 'CAP_MISALIGNED', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：版本不在认可集合'),
    ('DECAY_DAYS', 'CALIB', 'calib', 'const', True, '30.0', 'float', '见 default（阈值/权重）', '', '', 'const_assign', 'md_cg/links.py', 'DECAY_DAYS', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：无观测半衰期（向初值回归）'),
    ('READ_MAX_BYTES', 'CALIB', 'calib', 'const', True, '51200', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/mcp_server.py', 'READ_MAX_BYTES', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：单次 read 返回字节上限（Pi⑦② 截断）'),
    ('READ_MAX_LINES', 'CALIB', 'calib', 'const', True, '2000', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/mcp_server.py', 'READ_MAX_LINES', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：单次 read 返回行数上限（Pi⑦② 截断）'),
    ('DEFAULT_RECENT_WINDOW', 'TUNE', 'tune', 'const', True, '200', 'int', '见 default（超时/时间窗）', '', '', 'const_assign', 'md_cg/mdcg.py', 'DEFAULT_RECENT_WINDOW', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('GLOBAL_CAP', 'TUNE', 'tune', 'const', True, '500', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/mdcg.py', 'GLOBAL_CAP', 'uncalibrated', '全量回退的读取上限，对齐 sqlite 版 `ORDER BY importance DESC, created_at DESC LIMIT 500`', 'unknown', ''),
    ('LAYER_BOOST_DEFAULT', 'CALIB', 'calib', 'const', False, "{'anchor': 0.2, 'self': 0.2, 'structural': 0.15, 'knowledge': 0.1, 'contextual': 0.05}", 'dict', '见 default（枚举/表）', '', '', 'const_assign', 'md_cg/mdcg.py', 'LAYER_BOOST_DEFAULT', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('NEG_COVERAGE_MAX', 'CALIB', 'calib', 'const', True, '3', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/mdcg.py', 'NEG_COVERAGE_MAX', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('NEG_MIN_TERM', 'CALIB', 'calib', 'const', True, '2', 'int', '见 default（阈值/权重）', '', '', 'const_assign', 'md_cg/mdcg.py', 'NEG_MIN_TERM', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('OBSERVATION_WINDOW_SEC', 'TUNE', 'tune', 'const', True, '3600.0', 'float', '见 default（超时/时间窗）', '', '', 'const_assign', 'md_cg/mdcg.py', 'OBSERVATION_WINDOW_SEC', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('SYNONYM_GROUPS_WEIGHTED', 'CALIB', 'calib', 'const', False, "[{'视觉': 1.0, '图像': 0.9, '图片': 0.9, '画面': 0.8, '影像': 0.7, '视像': 0.6}, {'语义': 1.0, '含义': 0.8, '意思': 0.8, '意义': 0.8, '概念': 0.7}, {'识别': 1.0, '检测': 0.9, '感知': 0.7, '探测': 0.7, '发现': 0.5}, {'转换': 1.0, '转化': 0.9, '变换': 0.8, '映射': 0.7}, {'实验': 1.0, '试验': 0.9, '验证': 0.6, '测试': 0.6, '实现': 0.4, '集成': 0.4}, {'评测': 1.0, '评估': 0.9, 'benchmark': 0.8, '基准': 0.7, '跑分': 0.6, '评审': 0.5, '考核': 0.5}, {'记忆': 1.0, '记录': 0.7, '库': 0.3}, {'智能': 1.0, '智能体': 0.8, 'AI': 0.7, '灵枢': 0.6}, {'语音': 1.0, '声音': 0.8, '音频': 0.8, '说话': 0.4}, {'对话': 1.0, '聊天': 0.8, '交流': 0.6}]", 'list', '见 default（枚举/表）', '', '', 'const_assign', 'md_cg/mdcg.py', 'SYNONYM_GROUPS_WEIGHTED', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('TIER_SPREAD', 'CALIB', 'calib', 'const', False, "'T2b_spread_activation'", 'str', '见 default（枚举/名称）', '', '', 'const_assign', 'md_cg/mdcg.py', 'TIER_SPREAD', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('_NORM_WORD_MEMO_CAP', 'TUNE', 'tune', 'const', True, '262144', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/mdcg.py', '_NORM_WORD_MEMO_CAP', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('DEFAULT_BUDGET', 'CALIB', 'calib', 'const', False, '1200', 'int', '见 default（预算）', '', '', 'const_assign', 'md_cg/mdcos.py', 'DEFAULT_BUDGET', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：recall 默认 token 预算'),
    ('DEFAULT_MAX_ITEM_TOKENS', 'CALIB', 'calib', 'const', True, '250', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/mdcos.py', 'DEFAULT_MAX_ITEM_TOKENS', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('TEMPORAL_GAMMA_ENV', 'CALIB', 'calib', 'const', False, "'MDCG_TEMPORAL_GAMMA'", 'str', '见 default（env名常量）', '', '', 'const_assign', 'md_cg/mdcos.py', 'TEMPORAL_GAMMA_ENV', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('TERMINAL_DECISION_STATUS', 'CALIB', 'calib', 'const', False, "('accepted', 'rejected', 'noop')", 'tuple', '见 default（枚举/表）', '', '', 'const_assign', 'md_cg/mdcos.py', 'TERMINAL_DECISION_STATUS', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('_LEDGER_WINDOW', 'TUNE', 'tune', 'const', True, '1000000', 'int', '见 default（超时/时间窗）', '', '', 'const_assign', 'md_cg/mdcos.py', '_LEDGER_WINDOW', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('MIN_SAMPLES', 'CALIB', 'calib', 'const', True, '5', 'int', '见 default（阈值/权重）', '', '', 'const_assign', 'md_cg/metacognition.py', 'MIN_SAMPLES', 'uncalibrated', 'GAP_UNDERCONFIDENT = -0.15   # 过度保守：期望 - 实际 < 此值', 'unknown', '源码注释：样本不足 → insufficient_data'),
    ('GROUP_BATCH', 'TUNE', 'tune', 'const', False, "'batch'", 'str', '见 default（枚举/名称）', '', '', 'const_assign', 'md_cg/mreview/bundle.py', 'GROUP_BATCH', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('COLD_IMPORTANCE_MIN', 'CALIB', 'calib', 'const', True, '0.6', 'float', '见 default（阈值/权重）', '', '', 'const_assign', 'md_cg/mreview/candidates.py', 'COLD_IMPORTANCE_MIN', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：冷节点抽样门槛（importance 解析失败按 0 计）'),
    ('BATCH_DEFAULT', 'TUNE', 'tune', 'const', False, "'m4-role'", 'str', '见 default（枚举/名称）', '', '', 'const_assign', 'md_cg/mreview/govern.py', 'BATCH_DEFAULT', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('MIN_FLOW_SENTENCES', 'CALIB', 'calib', 'const', True, '2', 'int', '见 default（阈值/权重）', '', '', 'const_assign', 'md_cg/mreview/locate.py', 'MIN_FLOW_SENTENCES', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('SNIPPET_MAX', 'CALIB', 'calib', 'const', True, '120', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/mreview/locate.py', 'SNIPPET_MAX', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('TERMINAL_STATES', 'CALIB', 'calib', 'const', False, "('done', 'error', 'timeout', 'killed')", 'tuple', '见 default（枚举/表）', '', '', 'const_assign', 'md_cg/mreview/pipeline.py', 'TERMINAL_STATES', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('ELEMENT_TERM_MIN', 'CALIB', 'calib', 'const', True, '2', 'int', '见 default（阈值/权重）', '', '', 'const_assign', 'md_cg/nodefile.py', 'ELEMENT_TERM_MIN', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('FULL_TIME_WINDOW_MAX', 'TUNE', 'tune', 'const', True, '9999999999.0', 'float', '见 default（超时/时间窗）', '', '', 'const_assign', 'md_cg/nodefile.py', 'FULL_TIME_WINDOW_MAX', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('FULL_TIME_WINDOW_MIN', 'TUNE', 'tune', 'const', True, '0.0', 'float', '见 default（超时/时间窗）', '', '', 'const_assign', 'md_cg/nodefile.py', 'FULL_TIME_WINDOW_MIN', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('FULL_TIME_WINDOW_TEXT', 'TUNE', 'tune', 'const', False, "'全时窗（任意时刻成立）'", 'str', '见 default（枚举/名称）', '', '', 'const_assign', 'md_cg/nodefile.py', 'FULL_TIME_WINDOW_TEXT', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('POOL_INDEX', 'CALIB', 'calib', 'const', False, "'index'", 'str', '见 default（枚举/名称）', '', '', 'const_assign', 'md_cg/pooling.py', 'POOL_INDEX', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('POOL_KNOWLEDGE', 'CALIB', 'calib', 'const', False, "'knowledge'", 'str', '见 default（枚举/名称）', '', '', 'const_assign', 'md_cg/pooling.py', 'POOL_KNOWLEDGE', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('POOL_NEGATIVE', 'CALIB', 'calib', 'const', False, "'negative'", 'str', '见 default（枚举/名称）', '', '', 'const_assign', 'md_cg/pooling.py', 'POOL_NEGATIVE', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('_RATIO_EPS', 'TUNE', 'tune', 'const', True, '1e-09', 'float', '见 default（阈值/权重）', '', '', 'const_assign', 'md_cg/pooling.py', '_RATIO_EPS', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('EDGE_BOOST', 'CALIB', 'calib', 'const', True, '0.05', 'float', '见 default（阈值/权重）', '', '', 'const_assign', 'md_cg/predict.py', 'EDGE_BOOST', 'calibrating', 'MIN_SAMPLES = 50            # D-006 最低样本量', 'unknown', '源码注释：命中 → 因果/时序边置信度增量'),
    ('HIT_HISTORY_MAX', 'CALIB', 'calib', 'const', True, '200', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/predict.py', 'HIT_HISTORY_MAX', 'calibrating', 'MIN_SAMPLES = 50            # D-006 最低样本量', 'unknown', '源码注释：命中历史滚动窗口'),
    ('LEARN_MAX_STEPS', 'CALIB', 'calib', 'const', True, '8', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/predict.py', 'LEARN_MAX_STEPS', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('MAX_BRANCHES_DEFAULT', 'CALIB', 'calib', 'const', True, '5', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/predict.py', 'MAX_BRANCHES_DEFAULT', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('MAX_BRANCHES_HARD', 'CALIB', 'calib', 'const', True, '32', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/predict.py', 'MAX_BRANCHES_HARD', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('MIN_SAMPLES', 'CALIB', 'calib', 'const', True, '50', 'int', '见 default（阈值/权重）', '', '', 'const_assign', 'md_cg/predict.py', 'MIN_SAMPLES', 'calibrating', 'MIN_SAMPLES = 50            # D-006 最低样本量', 'unknown', '源码注释：D-006 最低样本量'),
    ('PREFERENCE_THRESHOLD', 'CALIB', 'calib', 'const', True, '0.5', 'float', '见 default（阈值/权重）', '', '', 'const_assign', 'md_cg/predict.py', 'PREFERENCE_THRESHOLD', 'uncalibrated', 'PREFERENCE_THRESHOLD = 0.5  # D-005 偏好权重准入线', 'unknown', '源码注释：D-005 偏好权重准入线'),
    ('SEMANTIC_MIN_SIM', 'CALIB', 'calib', 'const', True, '0.05', 'float', '见 default（阈值/权重）', '', '', 'const_assign', 'md_cg/predict.py', 'SEMANTIC_MIN_SIM', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('SEMANTIC_TOP_K', 'TUNE', 'tune', 'const', True, '5', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/predict.py', 'SEMANTIC_TOP_K', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('MIN_DISCRIM', 'CALIB', 'calib', 'const', True, '0.1', 'float', '见 default（阈值/权重）', '', '', 'const_assign', 'md_cg/progressive.py', 'MIN_DISCRIM', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('DEFAULT_FIND_LIMIT', 'TUNE', 'tune', 'const', True, '50', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/provenance.py', 'DEFAULT_FIND_LIMIT', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('MAX_FIND_LIMIT', 'TUNE', 'tune', 'const', True, '500', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/provenance.py', 'MAX_FIND_LIMIT', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('_LOCK_TIMEOUT', 'TUNE', 'tune', 'const', True, '2.0', 'float', '见 default（超时/时间窗）', '', '', 'const_assign', 'md_cg/provenance.py', '_LOCK_TIMEOUT', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('DIFFUSE_MAX_FACTOR', 'CALIB', 'calib', 'const', True, '3', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/reach.py', 'DIFFUSE_MAX_FACTOR', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('_FRESH_MAX', 'TUNE', 'tune', 'const', True, '500', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/reach.py', '_FRESH_MAX', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('SAMPLE_CAP', 'TUNE', 'tune', 'const', True, '20', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/reconcile.py', 'SAMPLE_CAP', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('MAX_CHECK', 'CALIB', 'calib', 'const', True, '2000', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/refindex.py', 'MAX_CHECK', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：巡检节点上限（超出报 truncated，不静默截断）'),
    ('CALIBRATE_CAP', 'TUNE', 'tune', 'const', True, '200', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/refine.py', 'CALIBRATE_CAP', 'calibrating', '样本量校准：目标产出候选数 / 有界爬坡上限（样本量非唯一杠杆，故设上限）', 'unknown', ''),
    ('EXCERPT_MAX', 'CALIB', 'calib', 'const', True, '4000', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/refine.py', 'EXCERPT_MAX', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('GATE_MIN_PASS_RATE', 'CALIB', 'calib', 'const', True, '0.9', 'float', '见 default（阈值/权重）', '', '', 'const_assign', 'md_cg/refine.py', 'GATE_MIN_PASS_RATE', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('CONTAMINATION', 'CALIB', 'calib', 'const', False, "{'contradiction': ('high', ('weaken', 'demote')), 'expired': ('high', ('weaken', 'demote')), 'not_yet': ('info', ('hint',)), 'duplicate': ('medium', ('hint',)), 'orphan_noise': ('low', ('weaken', 'demote')), 'unverified': ('info', ('hint',))}", 'dict', '见 default（枚举/表）', '', '', 'const_assign', 'md_cg/scrub.py', 'CONTAMINATION', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('DEFAULT_HOPS', 'TUNE', 'tune', 'const', True, '2', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/scrub.py', 'DEFAULT_HOPS', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('MAX_ASSOC_SCAN', 'CALIB', 'calib', 'const', True, '600', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/scrub.py', 'MAX_ASSOC_SCAN', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：词法近邻比对上限（全库扫描保护）'),
    ('MAX_BINS_REPORT', 'CALIB', 'calib', 'const', True, '4', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/scrub.py', 'MAX_BINS_REPORT', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('MAX_OFFSET', 'CALIB', 'calib', 'const', True, '0.15', 'float', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/scrub.py', 'MAX_OFFSET', 'uncalibrated', 'MAX_OFFSET = 0.15            # 校准偏置上限（一次最多挪这么多）', 'unknown', '源码注释：校准偏置上限（一次最多挪这么多）'),
    ('STRATUM_WEIGHTS', 'CALIB', 'calib', 'const', False, "{'stale': 0.2, 'low_conf': 0.2, 'disputed': 0.15, 'unverified': 0.15, 'orphan': 0.1, 'hot': 0.1, 'random': 0.1}", 'dict', '见 default（枚举/表）', '', '', 'const_assign', 'md_cg/scrub.py', 'STRATUM_WEIGHTS', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('DEFAULT_SENSITIVITY', 'CALIB', 'calib', 'const', False, "'internal'", 'str', '见 default（枚举/名称）', '', '', 'const_assign', 'md_cg/security.py', 'DEFAULT_SENSITIVITY', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('SENSITIVITY_ORDER', 'CALIB', 'calib', 'const', False, "('public', 'internal', 'restricted', 'private', 'secret')", 'tuple', '见 default（枚举/表）', '', '', 'const_assign', 'md_cg/security.py', 'SENSITIVITY_ORDER', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('RECENT_WINDOW', 'TUNE', 'tune', 'const', True, '20', 'int', '见 default（超时/时间窗）', '', '', 'const_assign', 'md_cg/self_state.py', 'RECENT_WINDOW', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('DEFAULT_LOCK_TIMEOUT', 'TUNE', 'tune', 'const', True, '30.0', 'float', '见 default（超时/时间窗）', '', '', 'const_assign', 'md_cg/sleep.py', 'DEFAULT_LOCK_TIMEOUT', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('_GIT_TIMEOUT_S', 'TUNE', 'tune', 'const', True, '120', 'int', '见 default（超时/时间窗）', '', '', 'const_assign', 'md_cg/sleep.py', '_GIT_TIMEOUT_S', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('SESSION_SENSITIVITY', 'CALIB', 'calib', 'const', False, "'private'", 'str', '见 default（枚举/名称）', '', '', 'const_assign', 'md_cg/sources.py', 'SESSION_SENSITIVITY', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('CHUNK', 'TUNE', 'tune', 'const', True, '1048576', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/srcindex.py', 'CHUNK', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：文件哈希分块（大文件不整读进内存）'),
    ('_BAD_ROW_SAMPLE_CAP', 'TUNE', 'tune', 'const', True, '8', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/state_events.py', '_BAD_ROW_SAMPLE_CAP', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('MAX_IDS', 'CALIB', 'calib', 'const', True, '50', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/statushdr.py', 'MAX_IDS', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('_CAP_HINT', 'TUNE', 'tune', 'const', False, "'条件命中 %s 条超过单次扫描限额 max_scan=%s，已按时间倒序保留近期 %s 条（截断不静默）：请细化生效条件/不适用条件（如 session/layer/time_window）收窄命中集，或按设计稿建立条件索引（docs/plans/stg条件化与结构索引_设计_v0.1.md）——不要调大 max_scan 数值。'", 'str', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/stg.py', '_CAP_HINT', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('MAX_DEPTH_HARD', 'TUNE', 'tune', 'const', True, '64', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/subgraph.py', 'MAX_DEPTH_HARD', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：工程硬截断上限（防止畸形数据把遍历拖爆）'),
    ('MAX_NODES_DEFAULT', 'CALIB', 'calib', 'const', True, '2000', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/subgraph.py', 'MAX_NODES_DEFAULT', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：单次展开的节点上限'),
    ('RECON_MAX_ANCHORS', 'CALIB', 'calib', 'const', True, '12', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/subgraph.py', 'RECON_MAX_ANCHORS', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：锚点上限'),
    ('RECON_MAX_NODES', 'CALIB', 'calib', 'const', True, '80', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/subgraph.py', 'RECON_MAX_NODES', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：单次扫描节点上限（防 O(N) 读盘爆炸）'),
    ('RECON_MIN_SCORE', 'CALIB', 'calib', 'const', True, '0.15', 'float', '见 default（阈值/权重）', '', '', 'const_assign', 'md_cg/subgraph.py', 'RECON_MIN_SCORE', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：词面命中下限（低于此不算锚点）'),
    ('RECON_NEIGHBOR_LIMIT', 'TUNE', 'tune', 'const', True, '24', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/subgraph.py', 'RECON_NEIGHBOR_LIMIT', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：每锚点取的邻居上限'),
    ('SEP_MAX_COND_OVERLAP', 'CALIB', 'calib', 'const', True, '0.35', 'float', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/subgraph.py', 'SEP_MAX_COND_OVERLAP', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：条件重合上限（越高＝条件越同，就该合并而非分离）'),
    ('SEP_MAX_NODES', 'CALIB', 'calib', 'const', True, '400', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/subgraph.py', 'SEP_MAX_NODES', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：单次扫描节点上限（防 O(N²) 读盘爆炸）'),
    ('SEP_MAX_PAIRS', 'CALIB', 'calib', 'const', True, '50', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/subgraph.py', 'SEP_MAX_PAIRS', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：单次返回/落库的候选对上限'),
    ('SEP_MIN_JACCARD', 'CALIB', 'calib', 'const', True, '0.55', 'float', '见 default（阈值/权重）', '', '', 'const_assign', 'md_cg/subgraph.py', 'SEP_MIN_JACCARD', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：内容相似度下限（越高＝越像，才值得谈分离）'),
    ('DEFAULT_BEAT_INTERVAL', 'TUNE', 'tune', 'const', True, '600.0', 'float', '见 default（超时/时间窗）', '', '', 'const_assign', 'md_cg/sustain.py', 'DEFAULT_BEAT_INTERVAL', 'uncalibrated', 'DEFAULT_BEAT_INTERVAL = 600.0     # 心跳间隔 10min（对齐 mutual-sustain-loop）', 'unknown', '源码注释：心跳间隔 10min（对齐 mutual-sustain-loop）'),
    ('DEFAULT_EVOLVE_INTERVAL', 'TUNE', 'tune', 'const', True, '7200.0', 'float', '见 default（超时/时间窗）', '', '', 'const_assign', 'md_cg/sustain.py', 'DEFAULT_EVOLVE_INTERVAL', 'uncalibrated', 'DEFAULT_BEAT_INTERVAL = 600.0     # 心跳间隔 10min（对齐 mutual-sustain-loop）；DEFAULT_SCRUB_INTERVAL = 3600.0   # 记忆自净（抽查/去污染/校准）1h', 'unknown', '源码注释：演化巡检（固化/重要性候选盘点）2h；只读'),
    ('DEFAULT_FRESH_TIMEOUT', 'TUNE', 'tune', 'const', True, '60.0', 'float', '见 default（超时/时间窗）', '', '', 'const_assign', 'md_cg/sustain.py', 'DEFAULT_FRESH_TIMEOUT', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：拉起后等待对端戳变新鲜的窗口'),
    ('DEFAULT_HEAL_INTERVAL', 'TUNE', 'tune', 'const', True, '300.0', 'float', '见 default（超时/时间窗）', '', '', 'const_assign', 'md_cg/sustain.py', 'DEFAULT_HEAL_INTERVAL', 'uncalibrated', 'DEFAULT_BEAT_INTERVAL = 600.0     # 心跳间隔 10min（对齐 mutual-sustain-loop）', 'unknown', '源码注释：自愈巡检 5min'),
    ('DEFAULT_SCRUB_INTERVAL', 'TUNE', 'tune', 'const', True, '3600.0', 'float', '见 default（超时/时间窗）', '', '', 'const_assign', 'md_cg/sustain.py', 'DEFAULT_SCRUB_INTERVAL', 'uncalibrated', 'DEFAULT_BEAT_INTERVAL = 600.0     # 心跳间隔 10min（对齐 mutual-sustain-loop）；DEFAULT_SCRUB_INTERVAL = 3600.0   # 记忆自净（抽查/去污染/校准）1h', 'unknown', '源码注释：记忆自净（抽查/去污染/校准）1h'),
    ('DEFAULT_TIDY_INTERVAL', 'TUNE', 'tune', 'const', True, '21600.0', 'float', '见 default（超时/时间窗）', '', '', 'const_assign', 'md_cg/sustain.py', 'DEFAULT_TIDY_INTERVAL', 'uncalibrated', 'DEFAULT_SCRUB_INTERVAL = 3600.0   # 记忆自净（抽查/去污染/校准）1h', 'unknown', '源码注释：整理巡检（contextual 同构组聚合）6h'),
    ('HEAL_BACKOFF_MAX', 'CALIB', 'calib', 'const', True, '3600.0', 'float', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/sustain.py', 'HEAL_BACKOFF_MAX', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：退避上限 1h'),
    ('HEARTBEAT_KEEP_SHARDS', 'TUNE', 'tune', 'const', True, '4', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/sustain.py', 'HEARTBEAT_KEEP_SHARDS', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：归档分片保留数（≤0 不淘汰；淘汰必留痕）'),
    ('TICK_INTERVAL_ATTRS', 'TUNE', 'tune', 'const', False, "(('beat', 'beat_interval'), ('heal', 'heal_interval'), ('scrub', 'scrub_interval'), ('evolve', 'evolve_interval'), ('tidy', 'tidy_interval'), ('sleep', 'sleep_interval'))", 'tuple', '见 default（超时/时间窗）', '', '', 'const_assign', 'md_cg/sustain.py', 'TICK_INTERVAL_ATTRS', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('TICK_STALE_MIN_S', 'CALIB', 'calib', 'const', True, '1800.0', 'float', '见 default（阈值/权重）', '', '', 'const_assign', 'md_cg/sustain.py', 'TICK_STALE_MIN_S', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('ESCAPE_OPS', 'TUNE', 'tune', 'const', False, "('theory',)", 'tuple', '见 default（枚举/表）', '', '', 'const_assign', 'md_cg/theory.py', 'ESCAPE_OPS', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('CORE_PRIVATE_SENSITIVITIES', 'CALIB', 'calib', 'const', False, "('private', 'secret')", 'tuple', '见 default（枚举/表）', '', '', 'const_assign', 'md_cg/tokens.py', 'CORE_PRIVATE_SENSITIVITIES', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('TOKEN_LOCK_TIMEOUT', 'TUNE', 'tune', 'const', True, '10.0', 'float', '见 default（超时/时间窗）', '', '', 'const_assign', 'md_cg/tokens.py', 'TOKEN_LOCK_TIMEOUT', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('GENERIC_LIMIT', 'TUNE', 'tune', 'const', True, '24', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/tool_face.py', 'GENERIC_LIMIT', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：通用参数（k/limit/tags/importance…）保留首段长度'),
    ('OP_SPECIFIC_LIMIT', 'TUNE', 'tune', 'const', True, '12', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/tool_face.py', 'OP_SPECIFIC_LIMIT', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：op 专属参数（长尾）压缩长度；超此长度整体外置'),
    ('HISTORY_KEEP', 'TUNE', 'tune', 'const', True, '20', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/trust.py', 'HISTORY_KEEP', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('MAX_DEPS', 'CALIB', 'calib', 'const', True, '32', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/trust.py', 'MAX_DEPS', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('MAX_NODES_DEFAULT', 'CALIB', 'calib', 'const', True, '500', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/trust.py', 'MAX_NODES_DEFAULT', 'uncalibrated', '多跳传播的节点上限（对齐 subgraph.MAX_NODES_DEFAULT 的量级）', 'unknown', ''),
    ('OBSERVED_WINDOW_FIELD', 'TUNE', 'tune', 'const', False, "'time_window'", 'str', '见 default（枚举/名称）', '', '', 'const_assign', 'md_cg/trust.py', 'OBSERVED_WINDOW_FIELD', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('_MS_EPOCH_THRESHOLD', 'TUNE', 'tune', 'const', True, '100000000000.0', 'float', '见 default（阈值/权重）', '', '', 'const_assign', 'md_cg/trust.py', '_MS_EPOCH_THRESHOLD', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('DEFAULT_MAX_TOKENS', 'CALIB', 'calib', 'const', True, '200000', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/units.py', 'DEFAULT_MAX_TOKENS', 'calibrating', '复核委派的 completion 预算。**必须对齐统一默认（文档：最大输出 200000）**——；实测 2048 → reasoning 2048 / content 空；16384 → 时好时坏；200000 → 正常出裁决。', 'unknown', ''),
    ('RESERVED_DEVICE_NAMES', 'CALIB', 'calib', 'const', False, "('CON', 'PRN', 'AUX', 'NUL', 'COM1', 'COM2', 'COM3', 'COM4', 'COM5', 'COM6', 'COM7', 'COM8', 'COM9', 'LPT1', 'LPT2', 'LPT3', 'LPT4', 'LPT5', 'LPT6', 'LPT7', 'LPT8', 'LPT9')", 'tuple', '见 default（其它）', '', '', 'const_assign', 'md_cg/units.py', 'RESERVED_DEVICE_NAMES', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('TERMINAL_STATES', 'CALIB', 'calib', 'const', False, "('done', 'error', 'timeout', 'killed')", 'tuple', '见 default（枚举/表）', '', '', 'const_assign', 'md_cg/units.py', 'TERMINAL_STATES', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('_MAX_CP', 'TUNE', 'tune', 'const', True, '1114111', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/units.py', '_MAX_CP', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('BATCH_DEFAULT', 'TUNE', 'tune', 'const', False, "'visevid'", 'str', '见 default（枚举/名称）', '', '', 'const_assign', 'md_cg/vision_evidence.py', 'BATCH_DEFAULT', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('AMBIGUOUS_SENSES', 'CALIB', 'calib', 'const', False, "{'苹果': [('水果', '蔷薇科植物的果实，富含维生素，有红富士/金帅等品种'), ('公司', 'Apple 科技公司，iPhone/Mac 的制造商'), ('颜色/品牌', '苹果绿（颜色）、苹果牌（商标）')], '变量': [('数学', '代数中可变化的量，用字母表示，如 x、y'), ('编程', '存储值的命名位置，数据类型决定操作')], '函数': [('数学', '输入到输出的映射关系，如 y=f(x)'), ('编程', '封装可复用逻辑的代码块（输入→处理→输出）')], '循环': [('编程', '重复执行的代码结构（for/while）'), ('系统/生态', '自我增强回路、负反馈、物质能量循环'), ('日常', '周而复始的过程，如昼夜循环')], '对象': [('编程', '面向对象中的实例（类实例化）'), ('哲学/语言学', '认识或行为的客体（相对主体）')], '字符': [('编程', '单个符号的编码单元（如 ASCII 字符）'), ('语文', '文字符号，汉字/字母/标点')], '模型': [('科学', '对现实的抽象表示（物理模型/数学模型）'), ('AI', '机器学习模型、大模型（参数化函数）')], '操作': [('编程', '对数据的指令/运算（如文件操作）'), ('日常', '动作/行为（操作机器、操作流程）')], '接口': [('编程', '组件间的交互约定（API/接口方法）'), ('工程', '设备间的连接界面（USB/HDMI）')], '框架': [('编程', '开发骨架/代码结构（如 Web 框架）'), ('日常/建筑', '支撑结构、制度框架')]}", 'dict', '见 default（枚举/表）', '', '', 'const_assign', 'md_cg/whitebox_kb/wisdom/chat_engine.py', 'AMBIGUOUS_SENSES', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('_CONVERGE_LIMIT', 'TUNE', 'tune', 'const', True, '3', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/whitebox_kb/wisdom/chat_engine.py', '_CONVERGE_LIMIT', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('TIMEOUT', 'TUNE', 'tune', 'const', True, '20', 'int', '见 default（超时/时间窗）', '', '', 'const_assign', 'md_cg/whitebox_kb/wisdom/code_test_runner.py', 'TIMEOUT', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：秒'),
    ('GPU_THRESHOLD', 'CALIB', 'calib', 'const', True, '50000', 'int', '见 default（阈值/权重）', '', '', 'const_assign', 'md_cg/whitebox_kb/wisdom/cspmn.py', 'GPU_THRESHOLD', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：N ≥ 5万 → 尝试 GPU（规模感知：矩阵乘占比主导后 GPU 显效）'),
    ('MAX_DEPTH', 'TUNE', 'tune', 'const', True, '3', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/whitebox_kb/wisdom/csre.py', 'MAX_DEPTH', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：智能论 3.12 递归深度约束（超出 = structural_blindspot）'),
    ('FISHING_SENSES', 'CALIB', 'calib', 'const', False, "{'sport': ['喜欢', '爱好', '周末', '爸爸', '鱼竿', '钓到', '河边', '湖', '海钓', '钓鱼吧', '钓鱼了', '钓鱼呀', '去钓鱼', '钓鱼场', '钓鱼运动', '钓鱼比赛'], 'security': ['链接', '邮件', '网站', '短信', '诈骗', '点击', '收到', '恶意', '木马', '钓鱼链接', '钓鱼邮件', '钓鱼网站'], 'troll': ['主播', '带节奏', '引战', '弹幕', '他在钓', '钓鱼执法']}", 'dict', '见 default（枚举/表）', '', '', 'const_assign', 'md_cg/whitebox_kb/wisdom/danmaku_audit.py', 'FISHING_SENSES', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('RATE_LIMIT_SECONDS', 'TUNE', 'tune', 'const', True, '3.0', 'float', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/whitebox_kb/wisdom/danmaku_bridge.py', 'RATE_LIMIT_SECONDS', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('MIN_ACCEPT_SCORE', 'CALIB', 'calib', 'const', True, '5', 'int', '见 default（阈值/权重）', '', '', 'const_assign', 'md_cg/whitebox_kb/wisdom/navigate.py', 'MIN_ACCEPT_SCORE', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：M1.2 四态边界：低于此分的候选不授予执行资格'),
    ('SEED_MIN_ACCEPT_SCORE', 'CALIB', 'calib', 'const', True, '3', 'int', '见 default（阈值/权重）', '', '', 'const_assign', 'md_cg/whitebox_kb/wisdom/navigate.py', 'SEED_MIN_ACCEPT_SCORE', 'uncalibrated', '校准：正例 6-10 / 域外 1-4，阈值取 5 最大化间隔', 'unknown', '源码注释：导航种子/常识播种卡：T8 复查实证分数 3-4'),
    ('SIM_THRESHOLD', 'CALIB', 'calib', 'const', True, '0.1', 'float', '见 default（阈值/权重）', '', '', 'const_assign', 'md_cg/whitebox_kb/wisdom/pattern_separation.py', 'SIM_THRESHOLD', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：内容相似度阈值（灵枢记忆库感知节点间较高）'),
    ('_ROUTE_CACHE_TTL', 'TUNE', 'tune', 'const', True, '300.0', 'float', '见 default（超时/时间窗）', '', '', 'const_assign', 'md_cg/whitebox_kb/wisdom/semantic_translate.py', '_ROUTE_CACHE_TTL', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('_MAX_LEN', 'TUNE', 'tune', 'const', True, '300', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/whitebox_kb/wisdom/verify_answer.py', '_MAX_LEN', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：人话回答上限（整卡通常 900-1200 字）'),
    ('_MIN_LEN', 'TUNE', 'tune', 'const', True, '2', 'int', '见 default（阈值/权重）', '', '', 'const_assign', 'md_cg/whitebox_kb/wisdom/verify_answer.py', '_MIN_LEN', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('CONVERGE_WINDOW', 'TUNE', 'tune', 'const', True, '86400.0', 'float', '见 default（超时/时间窗）', '', '', 'const_assign', 'md_cg/writelimit.py', 'CONVERGE_WINDOW', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：同构聚合窗口（秒，24h）'),
    ('MAX_APPLY', 'CALIB', 'calib', 'const', True, '500', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/writelimit.py', 'MAX_APPLY', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：tidy 单次落盘成员数上限（防一次改爆）'),
    ('MAX_CONTENT', 'CALIB', 'calib', 'const', True, '200', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/writelimit.py', 'MAX_CONTENT', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：参与同构聚合的内容长度上限（字符）'),
    ('MIN_SKELETON', 'CALIB', 'calib', 'const', True, '4', 'int', '见 default（阈值/权重）', '', '', 'const_assign', 'md_cg/writelimit.py', 'MIN_SKELETON', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：模板骨架最短长度（防「好的/收到」误聚）'),
    ('RATE_MAX', 'CALIB', 'calib', 'const', True, '8', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'md_cg/writelimit.py', 'RATE_MAX', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：窗口内同 (layer, role) 最大写入数'),
    ('RATE_WINDOW', 'TUNE', 'tune', 'const', True, '60.0', 'float', '见 default（超时/时间窗）', '', '', 'const_assign', 'md_cg/writelimit.py', 'RATE_WINDOW', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：频率窗口（秒）'),
    ('DEGRADE_LIMIT', 'TUNE', 'tune', 'const', True, '3', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'scripts/bootstrap_watchdog.py', 'DEGRADE_LIMIT', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：连续错误轮次阈值'),
    ('BATCH_MAX', 'TUNE', 'tune', 'const', True, '400', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'scripts/check_publish_artifact.py', 'BATCH_MAX', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('TEXT_SIZE_LIMIT', 'TUNE', 'tune', 'const', True, '3145728', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'scripts/check_publish_artifact.py', 'TEXT_SIZE_LIMIT', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('UNSCANNED_ESCAPE', 'TUNE', 'tune', 'const', False, "'清单内文本件真实路径越出 --root（符号链接/链接点）'", 'str', '见 default（枚举/名称）', '', '', 'const_assign', 'scripts/check_publish_artifact.py', 'UNSCANNED_ESCAPE', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('HANDSHAKE_TIMEOUT', 'TUNE', 'tune', 'const', True, '180', 'int', '见 default（超时/时间窗）', '', '', 'const_assign', 'scripts/check_publish_smoke.py', 'HANDSHAKE_TIMEOUT', 'calibrating', '握手总预算：实测 1.3s（0.6.1 装机面），给足余量但不无限等。', 'unknown', ''),
    ('NPM_TIMEOUT', 'TUNE', 'tune', 'const', True, '600', 'int', '见 default（超时/时间窗）', '', '', 'const_assign', 'scripts/check_publish_smoke.py', 'NPM_TIMEOUT', 'calibrating', '握手总预算：实测 1.3s（0.6.1 装机面），给足余量但不无限等。', 'unknown', ''),
    ('CHUNK_MAX', 'TUNE', 'tune', 'const', True, '600', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'scripts/dsh_log_index.py', 'CHUNK_MAX', 'calibrating', '摘要线后被截掉。600 字取「摘要覆盖率 ≥1/3、章数不过爆」的平衡点（实测', 'unknown', ''),
    ('MAX_CP', 'CALIB', 'calib', 'const', True, '1114111', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'scripts/gen_id_charset_blocks.py', 'MAX_CP', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('ACTIVE_WINDOW_S', 'TUNE', 'tune', 'const', True, '300', 'int', '见 default（超时/时间窗）', '', '', 'const_assign', 'scripts/mdcg_verify_render_meta.py', 'ACTIVE_WINDOW_S', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：「新鲜写入」窗口：重建后落入此窗的旧 render 即活跃污染证据'),
    ('SNIPPET_MAX', 'CALIB', 'calib', 'const', True, '30', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'scripts/probe_b_state_events_v4.py', 'SNIPPET_MAX', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：证据短证硬上限（≤30 字）'),
    ('BIG_LIMIT', 'TUNE', 'tune', 'const', True, '1000000000', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'scripts/probe_c_ledger_integrity.py', 'BIG_LIMIT', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('ANCHOR_WINDOW', 'TUNE', 'tune', 'const', False, '[1.0, 100000000000.0]', 'list', '见 default（枚举/表）', '', '', 'const_assign', 'scripts/probe_d_retirement_discipline.py', 'ANCHOR_WINDOW', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('FULL_WINDOW_HI', 'TUNE', 'tune', 'const', True, '9999999999.0', 'float', '见 default（超时/时间窗）', '', '', 'const_assign', 'scripts/retr_time_coverage.py', 'FULL_WINDOW_HI', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('MAX_FILES', 'CALIB', 'calib', 'const', True, '500', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'scripts/review_reconcile.py', 'MAX_FILES', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('MAX_ITEMS', 'CALIB', 'calib', 'const', True, '2000', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'scripts/review_reconcile.py', 'MAX_ITEMS', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('MAX_NODES', 'CALIB', 'calib', 'const', True, '20000', 'int', '见 default（上限/条数）', '', '', 'const_assign', 'scripts/review_reconcile.py', 'MAX_NODES', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：check 的节点扫描上限（超出即 truncated，不静默）'),
    ('WINDOW_LIMIT', 'TUNE', 'tune', 'const', True, '10', 'int', '见 default（超时/时间窗）', '', '', 'const_assign', 'scripts/sync_zcode_session.py', 'WINDOW_LIMIT', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('WINDOW_TAIL_SCAN', 'TUNE', 'tune', 'const', True, '600', 'int', '见 default（超时/时间窗）', '', '', 'const_assign', 'scripts/sync_zcode_session.py', 'WINDOW_TAIL_SCAN', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：尾扫消息条数（每轮低开销；够覆盖 ≥10 轮）'),
    ('MIN_SENTINEL', 'CALIB', 'calib', 'const', True, '24', 'int', '见 default（阈值/权重）', '', '', 'const_assign', 'scripts/verify_injection_zcode_user.py', 'MIN_SENTINEL', 'uncalibrated', '无（未见标定注记）', 'unknown', '源码注释：哨兵最短长度：太短会与普通文本偶然相撞'),
    ('_FLOORS', 'TUNE', 'tune', 'const', False, "{'files': 420, 'text_open': 700, 'bin_open': 76, 'attr_open': 56, 'attr_text_rw': 4}", 'dict', '见 default（枚举/表）', '', '', 'const_assign', 'scripts/verify_open_encoding.py', '_FLOORS', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('REMINDER_TMPL', 'CALIB', 'calib', 'const', False, "'【灵枢·逢十轮提醒】本会话已完成 {n} 轮交互。按工作纪律第 16 条做一次**间歇归档**：把本段（近 10 轮）的核心修改——内容/原因/位置/验证结论——按 CCG 六要素调用 mdcg 写入记忆（cg op=write），写入后**读回确认**一次；不等任务收尾。'", 'str', '见 default（阈值/权重）', '', '', 'const_assign', 'scripts/zcode_window_hook.py', 'REMINDER_TMPL', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
    ('WINDOW_ACK_KEY', 'TUNE', 'tune', 'const', False, "'win'", 'str', '见 default（枚举/名称）', '', '', 'const_assign', 'scripts/zcode_window_hook.py', 'WINDOW_ACK_KEY', 'uncalibrated', '无（未见标定注记）', 'unknown', ''),
]

ENV_ROWS = [
    ('MDCG_RETRIEVAL_PIPELINE', 'CALIB', 'calib', 'env', True, 'None', 'str', 'off', 'MDCG_RETRIEVAL_PIPELINE', 'off', 'env_flag', 'md_cg/mdcg.py', '', 'uncalibrated', '由生成器自 AST 复核（第一批未见标定读数）；有效缺省（盘点文字，未 AST 复核）：未设 = 关（!= "1" 即旧行为）', 'unknown', ''),
    ('MDCG_GATE_S1_DOMAIN', 'CALIB', 'calib', 'env', True, "'1'", 'str', 'on', 'MDCG_GATE_S1_DOMAIN', 'on', 'env_literal', 'md_cg/mdcg.py', '', 'uncalibrated', '由生成器自 AST 复核（第一批未见标定读数）', 'unknown', ''),
    ('MDCG_GATE_S2_COND', 'CALIB', 'calib', 'env', True, "'1'", 'str', 'on', 'MDCG_GATE_S2_COND', 'on', 'env_literal', 'md_cg/mdcg.py', '', 'uncalibrated', '由生成器自 AST 复核（第一批未见标定读数）', 'unknown', ''),
    ('MDCG_GATE_S3_SPREAD', 'CALIB', 'calib', 'env', True, 'None', 'str', 'off', 'MDCG_GATE_S3_SPREAD', 'off', 'env_flag', 'md_cg/mdcg.py', '', 'uncalibrated', '由生成器自 AST 复核（第一批未见标定读数）；有效缺省（盘点文字，未 AST 复核）：未设 = 关（=="1" 才开）', 'unknown', ''),
    ('MDCG_GATE_S4_LAYER', 'CALIB', 'calib', 'env', True, 'None', 'str', 'off', 'MDCG_GATE_S4_LAYER', 'off', 'env_flag', 'md_cg/mdcg.py', '', 'uncalibrated', '由生成器自 AST 复核（第一批未见标定读数）；有效缺省（盘点文字，未 AST 复核）：未设 = 关', 'unknown', ''),
    ('MDCG_GATE_S5_NEG', 'CALIB', 'calib', 'env', True, 'None', 'str', 'off', 'MDCG_GATE_S5_NEG', 'off', 'env_flag', 'md_cg/mdcg.py', '', 'uncalibrated', '由生成器自 AST 复核（第一批未见标定读数）；有效缺省（盘点文字，未 AST 复核）：未设 = 关', 'unknown', ''),
    ('MDCG_GATE_S6_CROSSCHECK', 'CALIB', 'calib', 'env', True, 'None', 'str', 'off', 'MDCG_GATE_S6_CROSSCHECK', 'off', 'env_flag', 'md_cg/mdcg.py', '', 'uncalibrated', '由生成器自 AST 复核（第一批未见标定读数）；有效缺省（盘点文字，未 AST 复核）：未设 = 关', 'unknown', ''),
    ('MDCG_GATE_S7_POSTINGS', 'CALIB', 'calib', 'env', True, 'None', 'str', 'off', 'MDCG_GATE_S7_POSTINGS', 'off', 'env_flag', 'md_cg/mdcg.py', '', 'uncalibrated', '由生成器自 AST 复核（第一批未见标定读数）；有效缺省（盘点文字，未 AST 复核）：未设 = 关', 'unknown', ''),
    ('MDCG_GATE_S1B_BUCKET', 'CALIB', 'calib', 'env', True, 'None', 'str', 'off', 'MDCG_GATE_S1B_BUCKET', 'off', 'env_flag', 'md_cg/mdcg.py', '', 'uncalibrated', '由生成器自 AST 复核（第一批未见标定读数）；有效缺省（盘点文字，未 AST 复核）：未设 = 关', 'unknown', ''),
    ('MDCG_BUCKET_MIN_SIM', 'CALIB', 'calib', 'env', True, "'0.34'", 'str', 'value', 'MDCG_BUCKET_MIN_SIM', 'value', 'env_literal', 'md_cg/mdcg.py', '', 'uncalibrated', '由生成器自 AST 复核（第一批未见标定读数）', 'unknown', ''),
    ('MDCG_BUCKET_TOPK', 'CALIB', 'calib', 'env', True, "'3'", 'str', 'value', 'MDCG_BUCKET_TOPK', 'value', 'env_literal', 'md_cg/mdcg.py', '', 'uncalibrated', '由生成器自 AST 复核（第一批未见标定读数）', 'unknown', ''),
    ('MDCG_SPREAD_GAIN', 'CALIB', 'calib', 'env', True, "'0.2'", 'str', 'value', 'MDCG_SPREAD_GAIN', 'value', 'env_literal', 'md_cg/mdcg.py', '', 'uncalibrated', '由生成器自 AST 复核（第一批未见标定读数）', 'unknown', ''),
    ('MDCG_SPREAD_DECAY', 'CALIB', 'calib', 'env', True, "'0.5'", 'str', 'value', 'MDCG_SPREAD_DECAY', 'value', 'env_literal', 'md_cg/mdcg.py', '', 'uncalibrated', '由生成器自 AST 复核（第一批未见标定读数）', 'unknown', ''),
    ('MDCG_NEG_SIM', 'CALIB', 'calib', 'env', True, "'0.5'", 'str', 'value', 'MDCG_NEG_SIM', 'value', 'env_literal', 'md_cg/mdcg.py', '', 'uncalibrated', '由生成器自 AST 复核（第一批未见标定读数）', 'unknown', ''),
    ('MDCG_NEG_LAMBDA', 'CALIB', 'calib', 'env', True, "'0.5'", 'str', 'value', 'MDCG_NEG_LAMBDA', 'value', 'env_literal', 'md_cg/mdcg.py', '', 'uncalibrated', '由生成器自 AST 复核（第一批未见标定读数）', 'unknown', ''),
    ('MDCG_SPREAD_HOPS', 'TUNE', 'tune', 'env', True, "'2'", 'str', 'value', 'MDCG_SPREAD_HOPS', 'value', 'env_literal', 'md_cg/mdcg.py', '', 'uncalibrated', '由生成器自 AST 复核（第一批未见标定读数）', 'unknown', ''),
    ('MDCG_LAYER_BOOST', 'TUNE', 'tune', 'env', True, "''", 'str', 'unset', 'MDCG_LAYER_BOOST', 'unset', 'env_literal', 'md_cg/mdcg.py', '', 'uncalibrated', '由生成器自 AST 复核（第一批未见标定读数）', 'unknown', ''),
    ('MDCG_HOTCACHE', 'TUNE', 'tune', 'env', True, 'None', 'str', 'off', 'MDCG_HOTCACHE', 'off', 'env_flag', 'md_cg/mdcos.py', '', 'uncalibrated', '由生成器自 AST 复核（第一批未见标定读数）；有效缺省（盘点文字，未 AST 复核）：未设 = 关（=="1"）', 'unknown', ''),
    ('MDCG_HOTCACHE_MAX_NODES', 'CALIB', 'calib', 'env', True, 'None', 'str', 'value', 'MDCG_HOTCACHE_MAX_NODES', 'value', 'env_helper_default', 'md_cg/hotcache.py', 'MAX_NODES', 'uncalibrated', '由生成器自 AST 复核（第一批未见标定读数）；有效缺省（盘点文字，未 AST 复核）：未设 = 模块常量 MAX_NODES=256', 'unknown', ''),
    ('MDCG_HOTCACHE_MAX_QUERIES', 'TUNE', 'tune', 'env', True, 'None', 'str', 'value', 'MDCG_HOTCACHE_MAX_QUERIES', 'value', 'env_helper_default', 'md_cg/hotcache.py', 'MAX_QUERIES', 'uncalibrated', '由生成器自 AST 复核（第一批未见标定读数）；有效缺省（盘点文字，未 AST 复核）：未设 = 模块常量 MAX_QUERIES=64', 'unknown', ''),
    ('MDCG_READ_CACHE', 'TUNE', 'tune', 'env', True, "'1'", 'str', 'on', 'MDCG_READ_CACHE', 'on', 'env_literal', 'md_cg/readcache.py', '', 'uncalibrated', '由生成器自 AST 复核（第一批未见标定读数）', 'unknown', ''),
    ('MDCG_MCP_SURFACE', 'ENV', 'env', 'env', False, "'kernel'", 'str', 'enum', 'MDCG_MCP_SURFACE', 'enum', 'env_literal', 'md_cg/mcp_server.py', '', 'uncalibrated', "★ 跨侧同名分叉：本仓 md_cg/mcp_server.py::SURFACE 缺省 'kernel'；TS 侧 src/lib/mdcg_client.ts 缺省 'full'（写入通道 mdcg_remember 属细粒度工具，故插件侧必须 full）。两侧各有理由，属**待裁定/待文档并列**。；由生成器自 AST 复核（第一批未见标定读数）", 'unknown', ''),
    ('MDCG_CLEARANCE', 'ENV', 'env', 'env', False, "'internal'", 'str', 'enum', 'MDCG_CLEARANCE', 'enum', 'env_literal', 'md_cg/mcp_server.py', '', 'uncalibrated', "★ 跨侧同名分叉：本仓 md_cg/mcp_server.py::_build_principal 缺省 'internal'；TS 侧 src/index.ts config.mdcg.clearance 缺省 'private'。令牌优先时 MDCG_CLEARANCE 完全被令牌覆盖（代码已有 stderr 告警），但两侧缺省仍不一致。；由生成器自 AST 复核（第一批未见标定读数）", 'unknown', ''),
    ('MDCG_ACTOR', 'ENV', 'env', 'env', False, '["\'mcp-client\'", "\'swarm-cli\'"]', 'str', 'conflict', 'MDCG_ACTOR', 'conflict', 'env_literal', 'md_cg/evidence.py;md_cg/mcp_server.py', '', 'uncalibrated', '★ 生产面缺省分叉：["\'mcp-client\'", "\'swarm-cli\'"]', 'unknown', '★ 生产面缺省分叉：["\'mcp-client\'", "\'swarm-cli\'"]'),
    ('MDCG_TENANT', 'ENV', 'env', 'env', False, "'default'", 'str', 'enum', 'MDCG_TENANT', 'enum', 'env_literal', 'md_cg/evidence.py;md_cg/mcp_server.py', '', 'uncalibrated', '由生成器自 AST 复核（第一批未见标定读数）', 'unknown', ''),
    ('MDCG_TOOL_FACE', 'TUNE', 'tune', 'env', True, 'None', 'str', 'off', 'MDCG_TOOL_FACE', 'off', 'env_flag', 'md_cg/tool_face.py', '', 'uncalibrated', '由生成器自 AST 复核（第一批未见标定读数）；有效缺省（盘点文字，未 AST 复核）：未设 = 非 full（=="full" 才全开）', 'unknown', ''),
    ('MDCG_EXPORT_ROOT', 'ENV', 'env', 'env', False, 'None', 'str', 'fail-open', 'MDCG_EXPORT_ROOT', 'fail-open', 'env_helper_arg', 'md_cg/mcp_server.py', '', 'uncalibrated', '由生成器自 AST 复核（第一批未见标定读数）；有效缺省（盘点文字，未 AST 复核）：未设 = 放开（check_path_root 未配置即放行）', 'unknown', ''),
    ('MDCG_INGEST_ROOT', 'ENV', 'env', 'env', False, 'None', 'str', 'fail-open', 'MDCG_INGEST_ROOT', 'fail-open', 'env_helper_arg', 'md_cg/logref.py;md_cg/mcp_server.py', '', 'uncalibrated', '由生成器自 AST 复核（第一批未见标定读数）；有效缺省（盘点文字，未 AST 复核）：未设 = 放开（check_path_root 未配置即放行）', 'unknown', ''),
    ('AEIS_DB', 'ENV', 'env', 'env', False, '"os.path.join(\'data\', \'lingshu.db\')"', 'str', 'conflict', 'AEIS_DB', 'conflict', 'env_literal', 'md_cg/whitebox_kb/wisdom/danmaku_bridge.py;md_cg/whitebox_kb/wisdom/merge_subgraph.py;md_cg/whitebox_kb/wisdom/pattern_separation.py;md_cg/whitebox_kb/wisdom/scene_reconstruction.py', '', 'uncalibrated', '★ 跨仓同名分叉：本仓（脑内副本 md_cg/whitebox_kb/wisdom/*）缺省 = os.path.join(\'data\',\'lingshu.db\')（相对路径**落盘**库）；私域仓 <私域仓>/aeis/{server.py,mcp/server.py} 缺省 ":memory:"（内存库）。同名同义假设不成立——落盘 vs 不落盘。；由生成器自 AST 复核（第一批未见标定读数）', 'unknown', ''),
    ('AEIS_WORKSPACE', 'ENV', 'env', 'env', False, "''", 'str', 'value', 'AEIS_WORKSPACE', 'value', 'env_literal', 'md_cg/whitebox_kb/aeis_core/core.py', '', 'uncalibrated', '由生成器自 AST 复核（第一批未见标定读数）', 'unknown', ''),
    ('MDCG_SEMANTIC', 'TUNE', 'tune', 'env', True, 'None', 'str', 'off', 'MDCG_SEMANTIC', 'off', 'env_flag', 'md_cg/mdcg.py', '', 'uncalibrated', '由生成器自 AST 复核（第一批未见标定读数）；有效缺省（盘点文字，未 AST 复核）：未设 = 关（=="1"）', 'unknown', ''),
    ('MDCG_EN_ATOMS', 'TUNE', 'tune', 'env', True, "'0'", 'str', 'off', 'MDCG_EN_ATOMS', 'off', 'env_literal', 'md_cg/mdcg.py', '', 'uncalibrated', '由生成器自 AST 复核（第一批未见标定读数）', 'unknown', ''),
    ('MDCG_CN_GRAMS', 'TUNE', 'tune', 'env', True, 'None', 'str', 'on', 'MDCG_CN_GRAMS', 'on', 'env_flag', 'md_cg/mdcg.py', '', 'uncalibrated', '由生成器自 AST 复核（第一批未见标定读数）；有效缺省（盘点文字，未 AST 复核）：未设 = 开（!="0"）', 'unknown', ''),
    ('MDCG_CHAIN_TYPES', 'TUNE', 'tune', 'env', True, 'None', 'str', 'unset', 'MDCG_CHAIN_TYPES', 'unset', 'env_flag', 'md_cg/chain.py', '', 'uncalibrated', '由生成器自 AST 复核（第一批未见标定读数）；有效缺省（盘点文字，未 AST 复核）：未设 = CHAIN_TYPES_DEFAULT (causal, sequential, applies_to)', 'unknown', ''),
    ('MDCG_S7_FRESHNESS', 'TUNE', 'tune', 'env', True, 'None', 'str', 'on', 'MDCG_S7_FRESHNESS', 'on', 'env_flag', 'md_cg/mdcg.py', '', 'uncalibrated', '由生成器自 AST 复核（第一批未见标定读数）；有效缺省（盘点文字，未 AST 复核）：未设 = 走新鲜度（仅字面量 "skip" 跳过）', 'unknown', ''),
    ('MDCG_UNIFY_QUERY', 'CALIB', 'calib', 'env', True, "'0'", 'str', 'off', 'MDCG_UNIFY_QUERY', 'off', 'env_literal', 'md_cg/semantic/unify.py', '', 'uncalibrated', '由生成器自 AST 复核（第一批未见标定读数）', 'unknown', ''),
    ('MDCG_SCORE_MODE', 'CALIB', 'calib', 'env', True, "'legacy'", 'str', 'enum', 'MDCG_SCORE_MODE', 'enum', 'env_literal', 'md_cg/mdcg.py', '', 'uncalibrated', '由生成器自 AST 复核（第一批未见标定读数）', 'unknown', ''),
    ('MDCG_TEMPORAL_GAMMA', 'CALIB', 'calib', 'env', True, 'None', 'str', 'unset', 'MDCG_TEMPORAL_GAMMA', 'unset', 'env_flag', 'md_cg/mdcos.py', '', 'uncalibrated', '由生成器自 AST 复核（第一批未见标定读数）；有效缺省（盘点文字，未 AST 复核）：未设 = ln2/30天（由 links.DECAY_DAYS 派生）', 'unknown', ''),
    ('MDCG_WRITELIMIT', 'TUNE', 'tune', 'env', True, "'1'", 'str', 'on', 'MDCG_WRITELIMIT', 'on', 'env_literal', 'md_cg/writelimit.py', '', 'uncalibrated', '由生成器自 AST 复核（第一批未见标定读数）', 'unknown', ''),
    ('MDCG_RECONCILE', 'TUNE', 'tune', 'env', True, "''", 'str', 'on', 'MDCG_RECONCILE', 'on', 'env_literal', 'md_cg/reconcile.py', '', 'uncalibrated', '由生成器自 AST 复核（第一批未见标定读数）', 'unknown', ''),
    ('MDCG_REACH', 'CALIB', 'calib', 'env', True, 'None', 'str', 'off', 'MDCG_REACH', 'off', 'env_flag', 'md_cg/reach.py', '', 'uncalibrated', '由生成器自 AST 复核（第一批未见标定读数）；有效缺省（盘点文字，未 AST 复核）：未设 = 关（=="1"）', 'unknown', ''),
    ('MDCG_REACH_DIFFUSE', 'CALIB', 'calib', 'env', True, "'0'", 'str', 'off', 'MDCG_REACH_DIFFUSE', 'off', 'env_literal', 'md_cg/reach.py', '', 'uncalibrated', '由生成器自 AST 复核（第一批未见标定读数）', 'unknown', ''),
    ('MDCG_REACH_TTL', 'TUNE', 'tune', 'env', True, '600.0', 'float', 'value', 'MDCG_REACH_TTL', 'value', 'env_literal', 'md_cg/reach.py', '', 'uncalibrated', '由生成器自 AST 复核（第一批未见标定读数）', 'unknown', ''),
    ('MDCG_POOLING', 'CALIB', 'calib', 'env', True, 'None', 'str', 'off', 'MDCG_POOLING', 'off', 'env_flag', 'md_cg/pooling.py', '', 'uncalibrated', '由生成器自 AST 复核（第一批未见标定读数）；有效缺省（盘点文字，未 AST 复核）：未设 = 关（仅 1/on/true/yes/y 开）', 'unknown', ''),
    ('MDCG_PROPOSAL_EMOTION', 'CALIB', 'calib', 'env', True, 'None', 'str', 'off', 'MDCG_PROPOSAL_EMOTION', 'off', 'env_flag', 'md_cg/autonomy.py', '', 'uncalibrated', '由生成器自 AST 复核（第一批未见标定读数）；有效缺省（盘点文字，未 AST 复核）：未设 = 关', 'unknown', ''),
    ('MDCG_EXPLORE_BUDGET_MAX', 'TUNE', 'tune', 'env', True, 'None', 'str', 'unset', 'MDCG_EXPLORE_BUDGET_MAX', 'unset', 'env_flag', 'md_cg/autonomy.py', '', 'uncalibrated', '由生成器自 AST 复核（第一批未见标定读数）', 'unknown', ''),
    ('MDCG_EXPLORE_BUDGET_WINDOW', 'TUNE', 'tune', 'env', True, 'None', 'str', 'value', 'MDCG_EXPLORE_BUDGET_WINDOW', 'value', 'env_helper_default', 'md_cg/autonomy.py', 'BUDGET_WINDOW_DEFAULT', 'uncalibrated', '由生成器自 AST 复核（第一批未见标定读数）', 'unknown', ''),
    ('MDCG_D_META', 'TUNE', 'tune', 'env', True, "''", 'str', 'on', 'MDCG_D_META', 'on', 'env_literal', 'md_cg/d_meta.py', '', 'uncalibrated', '由生成器自 AST 复核（第一批未见标定读数）', 'unknown', ''),
    ('MDCG_STATUS_HEAD', 'TUNE', 'tune', 'env', True, 'None', 'str', 'on', 'MDCG_STATUS_HEAD', 'on', 'env_flag', 'md_cg/statushdr.py', '', 'uncalibrated', '由生成器自 AST 复核（第一批未见标定读数）；有效缺省（盘点文字，未 AST 复核）：未设 = **开**（0/false/no/off 关）', 'unknown', ''),
    ('MDCG_FRESHNESS', 'TUNE', 'tune', 'env', True, 'None', 'str', 'on', 'MDCG_FRESHNESS', 'on', 'env_flag', 'md_cg/freshness.py', '', 'uncalibrated', '由生成器自 AST 复核（第一批未见标定读数）；有效缺省（盘点文字，未 AST 复核）：未设 = **开**（0/false/no/off 关）', 'unknown', ''),
    ('MDCG_SUSTAIN', 'TUNE', 'tune', 'env', True, "'1'", 'str', 'on', 'MDCG_SUSTAIN', 'on', 'env_literal', 'md_cg/mcp_server.py', '', 'uncalibrated', '由生成器自 AST 复核（第一批未见标定读数）', 'unknown', ''),
    ('MDCG_HEARTBEAT_LEDGER', 'TUNE', 'tune', 'env', True, "'1'", 'str', 'on', 'MDCG_HEARTBEAT_LEDGER', 'on', 'env_literal', 'md_cg/sustain.py', '', 'uncalibrated', '由生成器自 AST 复核（第一批未见标定读数）', 'unknown', ''),
    ('PREDICTION_META_DIM', 'CALIB', 'calib', 'env', True, "'0'", 'str', 'value', 'PREDICTION_META_DIM', 'value', 'env_literal', 'md_cg/predict.py', '', 'uncalibrated', '由生成器自 AST 复核（第一批未见标定读数）', 'unknown', ''),
    ('PREDICTION_META_PROXY', 'CALIB', 'calib', 'env', True, "'unmodeled_growth'", 'str', 'enum', 'PREDICTION_META_PROXY', 'enum', 'env_literal', 'md_cg/predict.py', '', 'uncalibrated', '由生成器自 AST 复核（第一批未见标定读数）', 'unknown', ''),
    ('IMGSKILL_BACKEND', 'TUNE', 'tune', 'env', True, "'auto'", 'str', 'enum', 'IMGSKILL_BACKEND', 'enum', 'env_literal', 'md_cg/imgskill.py', '', 'uncalibrated', '由生成器自 AST 复核（第一批未见标定读数）', 'unknown', ''),
    ('IMGSKILL_PILLOW', 'TUNE', 'tune', 'env', True, 'None', 'str', 'on', 'IMGSKILL_PILLOW', 'on', 'env_flag', 'md_cg/imgskill.py', '', 'uncalibrated', '由生成器自 AST 复核（第一批未见标定读数）；有效缺省（盘点文字，未 AST 复核）：未设 = 允许（=="0" 显式禁用 Pillow 后端）', 'unknown', ''),
]

# 环境面**分类登记**（只登记「属于环境面」与值域类型；**不登记缺省值**）
# 字段：(name, kind, repo, domain, notes)
ENV_CATEGORY_ROWS = [
    ('AEIS_BGE_PATH', 'env', 'dsh-memory-main', '目录路径', '私域仓未检出同名读取点'),
    ('AEIS_DB', 'env', 'dsh-memory-main', 'DB 路径或 ":memory:"', '★与私域仓默认值分叉，见 AEIS 对照节'),
    ('AEIS_DESIGNER_KEY', 'env', 'dsh-memory-main', '密钥（敏感）', '三副本同名同义；值为敏感，不回显'),
    ('AEIS_WORKSPACE', 'env', 'dsh-memory-main', '目录路径', '两副本一致'),
    ('CLAUDE_SESSION_ID / ZCODE_SESSION_ID', 'env', 'dsh-memory-main', '字符串', ''),
    ('DMCG_HOME', 'env', 'dsh-memory-main', '目录路径', 'skills/ 面唯一 env'),
    ('DSH_HOME', 'env', 'dsh-memory-main', '目录路径', ''),
    ('DSH_SESSION_ID', 'env', 'dsh-memory-main', '字符串', ''),
    ('HIVE_API_KEY', 'env', 'dsh-memory-main', '密钥（敏感）', '单位复核面借用蜂巢键名'),
    ('IMGSKILL_MAGICK', 'env', 'dsh-memory-main', '可执行体路径或安装目录', '经 *_ENV 常量间接读取，朴素字面量扫描抓不到'),
    ('LINGSHU_DB', 'env', 'dsh-memory-main', 'DB 路径', '身体仓无同名读取点'),
    ('LINGSHU_KB', 'env', 'dsh-memory-main', '目录路径', ''),
    ('LINGSHU_PYTHON / LINGSHU_REPO', 'env', 'dsh-memory-main', '解释器路径 / 目录', ''),
    ('MAGICK_HOME / ImageMagick_HOME', 'env', 'dsh-memory-main', '目录路径', '经 *_ENV 常量间接读取，朴素字面量扫描抓不到'),
    ('MDCG_ACTOR', 'env', 'dsh-memory-main', '字符串', '★ 两处默认值不同（同一 env 名，默认分叉）'),
    ('MDCG_ARCHIVE_ROOT', 'env', 'dsh-memory-main', '目录路径', ''),
    ('MDCG_AUX_ROOT', 'env', 'dsh-memory-main', '目录路径', ''),
    ('MDCG_BRAIN_PYTHONPATH', 'env', 'dsh-memory-main', '路径列表', '★ 文档承诺 vs 代码读取错位（只在另一副本被读）'),
    ('MDCG_CAN_ADMIN', 'env', 'dsh-memory-main', 'bool 字符串 {1,true,True}', ''),
    ('MDCG_CAN_WRITE', 'env', 'dsh-memory-main', 'bool 字符串', ''),
    ('MDCG_CHILD_CWD', 'env', 'dsh-memory-main', '目录路径', '只在 TS 面定义/传递'),
    ('MDCG_CLEARANCE', 'env', 'dsh-memory-main', '枚举 {public,internal,restricted,private,secret}', ''),
    ('MDCG_CODE_TEST_CMD / MDCG_CODE_TEST_TIMEOUT', 'env', 'dsh-memory-main', '命令串 / 秒(int)', 'CODE_TEST_CMD 属权限面（执行外部命令）'),
    ('MDCG_DATA_ROOT', 'env', 'dsh-memory-main', '目录路径', ''),
    ('MDCG_DSH_SESSIONS_ROOT', 'env', 'dsh-memory-main', '目录路径', ''),
    ('MDCG_EXPORT_ROOT', 'env', 'dsh-memory-main', 'path 列表（os.pathsep 分隔）', '部署期写路径白名单'),
    ('MDCG_FRESHNESS_NOW', 'env', 'dsh-memory-main', 'float（可复算冻结口）', '供两侧探针逐位比对'),
    ('MDCG_GATE_SANDBOX_DIR', 'env', 'dsh-memory-main', '目录路径', ''),
    ('MDCG_HARNESS / MDCG_UNIT', 'env', 'dsh-memory-main', '字符串', '服务端身份面（同样有 MDCG_NODE_ID/MDCG_SWARM_DIR 归因面）'),
    ('MDCG_HIVE_JOBS', 'env', 'dsh-memory-main', '目录路径', ''),
    ('MDCG_INGEST_ROOT', 'env', 'dsh-memory-main', 'path 列表（os.pathsep 分隔）', '部署期写路径白名单'),
    ('MDCG_JUDGMENT_MANIFEST', 'env', 'dsh-memory-main', '文件路径', ''),
    ('MDCG_LEGACY_ENV_ADMIN', 'env', 'dsh-memory-main', 'bool 字符串', ''),
    ('MDCG_LEGACY_ENV_AUTH', 'env', 'dsh-memory-main', 'bool 字符串 {1,true,True}', ''),
    ('MDCG_LEGACY_ENV_AUTH 之外的插件 config.env 面', 'env', 'dsh-memory-main', '任意 env 键值表', '用户配置文件里可放任意 env——统一配置层需收口处'),
    ('MDCG_LINKS_FILE', 'env', 'dsh-memory-main', '文件路径', '文档写了但生产不读'),
    ('MDCG_LINKS_FILE / MDCG_SIGNERS_FILE 之外的测试面 env', 'env', 'dsh-memory-main', '—', '生产读取点极少、测试面占绝大多数'),
    ('MDCG_LLM_KEY / MDCG_LLM_BASE / MDCG_LLM_MODEL', 'env', 'dsh-memory-main', '密钥 / URL / 模型名', ''),
    ('MDCG_MASTER_KEY', 'env', 'dsh-memory-main', '密钥（敏感，hex）', '敏感值不回显'),
    ('MDCG_MCP_SURFACE', 'env', 'dsh-memory-main', '枚举 {kernel, full}', 'kernel 只暴露 cg/stg 两基元'),
    ('MDCG_POLICY_FILE', 'env', 'dsh-memory-main', '文件路径', ''),
    ('MDCG_PYTHON', 'env', 'dsh-memory-main', '解释器路径', '★ 动态键读取，朴素 grep 抓不到'),
    ('MDCG_REACH_INDEX', 'env', 'dsh-memory-main', '文件路径', ''),
    ('MDCG_REDTEAM_REQUIRED', 'env', 'dsh-memory-main', 'bool 语义字符串（非空即需红队）', ''),
    ('MDCG_REFLECT_KEY / MDCG_REFLECT_MODEL / MDCG_REFLECT_BASE', 'env', 'dsh-memory-main', '密钥 / 模型名 / URL', ''),
    ('MDCG_ROOT', 'env', 'dsh-memory-main', '目录路径', '双副本同名同义'),
    ('MDCG_SESSION', 'env', 'dsh-memory-main', '字符串', 'TS 面已改为「请求声明归因」优先（见 src/tools.ts 注）'),
    ('MDCG_SIGNERS_FILE / MDCG_SIGNER_KEY_FILE / MDCG_SIGNER_MODULE', 'env', 'dsh-memory-main', '文件路径 / 文件路径 / 模块名', ''),
    ('MDCG_STATE_ROOT', 'env', 'dsh-memory-main', '目录路径', ''),
    ('MDCG_SUSTAIN_DIR', 'env', 'dsh-memory-main', '目录路径', ''),
    ('MDCG_SUSTAIN_NAME', 'env', 'dsh-memory-main', '字符串', ''),
    ('MDCG_SWARM_DIR', 'env', 'dsh-memory-main', '目录路径', ''),
    ('MDCG_TENANT', 'env', 'dsh-memory-main', '租户名', "★ 注意：src/index.ts 另有 MDCG_TENANT 默认 'default'（插件 config.mdcg.tenant）"),
    ('MDCG_TENANT_REGISTRY', 'env', 'dsh-memory-main', '文件路径', ''),
    ('MDCG_TESTLOG_DIR', 'env', 'dsh-memory-main', '目录路径', ''),
    ('MDCG_THEORY_FILE / MDCG_THEORY', 'env', 'dsh-memory-main', '文件路径', ''),
    ('MDCG_TOKEN', 'env', 'dsh-memory-main', '令牌串（敏感）', '敏感值不回显'),
    ('MDCG_TOKEN_FILE', 'env', 'dsh-memory-main', '文件路径（内含令牌，敏感）', ''),
    ('MDCG_UNIFY_QUERY 之外的叙述性开关：MDCG_HOME/MDCG_IDENTITY/MDCG_LAYERS', 'env', 'dsh-memory-main', '—', '三者均属「提到但无本仓读取点」'),
    ('MDCG_UNIT_MODEL', 'env', 'dsh-memory-main', '模型名', ''),
    ('MDCG_VERIFIER_MODULES', 'env', 'dsh-memory-main', '模块名列表', ''),
    ('MDCG_VERIFY_KEY / MDCG_VERIFY_MODEL / MDCG_VERIFY_BASE', 'env', 'dsh-memory-main', '密钥 / 模型名 / URL', ''),
    ('MDCG_VISION_ROOT（遗留别名 MDCG_AEIS_ROOT）', 'env', 'dsh-memory-main', '目录路径', ''),
    ('MDCG_WHITEBOX_CMD / MDCG_WHITEBOX_ARGS / MDCG_WHITEBOX_TIMEOUT', 'env', 'dsh-memory-main', '字符串 / JSON 参数串 / 秒(float)', ''),
    ('OPENBLAS_NUM_THREADS', 'env', 'dsh-memory-main', 'int', '★ 只写不读的自我设值'),
    ('PYTHONUTF8', 'env', 'dsh-memory-main', '字符串', ''),
    ('WB_MD_ROOT', 'env', 'dsh-memory-main', '目录路径（必填式，2 处 os.environ["WB_MD_ROOT"] 硬取）', '与白箱知识库内迁面同源'),
    ('WHITEBOX_DB / MDCG_WHITEBOX_DB', 'env', 'dsh-memory-main', 'DB 路径', ''),
    ('cordis 补丁 profile :: AEIS_LIFECYCLE / AEIS_LIFECYCLE_INTERVAL', 'conf_key', 'dsh-memory-main', '—', ''),
    ('cordis 补丁 profile :: BOCHA_API_KEY', 'conf_key', 'dsh-memory-main', '字符串（敏感）', ''),
    ('cordis.yml :: 插件 config 段', 'conf_key', 'dsh-memory-main', '—', ''),
    ('paths.json :: data_root', 'conf_key', 'dsh-memory-main', '路径', ''),
    ('paths.json :: root', 'conf_key', 'dsh-memory-main', '路径', ''),
    ('policy.json :: forbidden', 'conf_key', 'dsh-memory-main', '正则数组', ''),
    ('policy.json :: required / required_labels', 'conf_key', 'dsh-memory-main', '正则数组 / 标签数组', ''),
    ('policy.json :: required_kinds', 'conf_key', 'dsh-memory-main', '字符串数组', ''),
    ('AEIS_DESIGNER_KEY', 'env', 'lingshu', '密钥（敏感）', ''),
    ('AEIS_HEX_NN', 'env', 'lingshu', '路径', ''),
    ('AEIS_WORKSPACE', 'env', 'lingshu', '路径', ''),
    ('BRAIN_PYTHON', 'env', 'lingshu', '解释器路径', ''),
    ('BRAIN_PYTHONPATH', 'env', 'lingshu', '路径列表', ''),
    ('BRAIN_ROOT', 'env', 'lingshu', '路径', ''),
    ('GH_TOKEN / GH_PROJECT_TOKEN / TRACKER / LABEL / DRY_RUN / OUT / REPO / SCRIPT_TESTS', 'env', 'lingshu', '混合', ''),
    ('GITHUB_ACTIONS / PR_TITLE', 'env', 'lingshu', '字符串', ''),
    ('LINGSHU_COMPONENT_ROOT', 'env', 'lingshu', '路径', ''),
    ('LINGSHU_DATA_ROOT', 'env', 'lingshu', '路径', ''),
    ('MDCG_BRAIN_PYTHONPATH', 'env', 'lingshu', '路径列表', ''),
    ('MDCG_LEGACY_ENV_AUTH / MDCG_CAN_ADMIN / MDCG_LEGACY_ENV_ADMIN', 'env', 'lingshu', 'bool 语义', ''),
    ('MDCG_ROOT', 'env', 'lingshu', '路径', ''),
    ('PYTHONUTF8 / PYTHONIOENCODING', 'env', 'lingshu', '字符串', ''),
]
# fmt: on

META = {
    "generated_from": "param_inventory.json",
    "const_count": 236,
    "const_dropped": 12,
    "env_count": 56,
    "env_skipped": 1,
    "env_category_count": 90,
}
